dist: focal
os: linux
language: minimal
arch: amd64

stages:
  - build
  - push

jobs:

  include:

    - stage: build
      name: 'build'
      language: minimal
      script:
        - make build

    - stage: push
      name: 'push'
      language: minimal
      script:
        - make build
      after_success:
        - docker images
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker tag py-httpd $DOCKER_USERNAME/py-httpd
        - docker tag py-httpd $DOCKER_USERNAME/py-httpd:$TRAVIS_BUILD_NUMBER
        - docker push $DOCKER_USERNAME/py-httpd
        - docker push $DOCKER_USERNAME/py-httpd:$TRAVIS_BUILD_NUMBER
